version: '2'
services:
  registry:
    image: registry:2 
    restart: always
    ports:
      - 5000:5000
    volumes:
      - registry/config/config.yml:/etc/docker/registry/config.yml
      - registry/config:/config
      - /tmp/registry:/var/lib/registry
    networks:
      registry_net:
        ipv4_address: 172.22.0.5
    depends_on:
      - auth
  auth:
    image: cesanta/docker_auth:1
    ports:
      - 5001:5001
    volumes:
      - registry_auth/config:/config
      - /tmp/log/docker_auth:/logs
    command: "--v=2 --alsologtostderr /config/config.yml"
    networks:
      registry_net:
        ipv4_address: 172.22.0.6

networks:
  registry_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
            
