version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
auth:
  token:
    realm: https://localhost:5001/auth  # auth endpoing (docker_auth)
    service: container_registry
    issuer: my_issuer                   # same as what is in docker_auth
    rootcertbundle: /config/cert.pem
health:
  storagediver:
    enabled: true
    interval: 10s
    threshold: 3
